version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    mac_address: ${MAC_PIHOLE}
    networks:
      macVlanNetwork:
        ipv4_address: ${IP_PIHOLE}
    dns:
      - 127.0.0.1
      - ${DNS1}
      - ${DNS2}
    ports:
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
      - 443/tcp
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_LOCAL_IPV4: ${IP_PIHOLE}
      PIHOLE_DNS_: ${DNS1};${DNS2}
      ADMIN_EMAIL: ${EMAIL}
      WEBPASSWORD: ${PASS}
      WEB_PORT: ${PORT}
      VIRTUAL_HOST: ${VIRTUALHOST}
      IPv6: 'False'
      DNSSEC: 'False'
      DNSMASQ_LISTENING: local
    volumes:
      - '${LOCALPATH}/${PATH_PIHOLE}/etc:/etc/pihole'
      - '${LOCALPATH}/${PATH_PIHOLE}/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

  unifi:
    container_name: unifi
    image: jacobalberty/unifi:${IMAGE_VERSION_UNIFI}
    hostname: unifi
    mac_address: ${MAC_UNIFI}
    networks:
      macVlanNetwork:
        ipv4_address: ${IP_UNIFI}
    dns:
      - 127.0.0.1
      - ${DNS1}
      - ${DNS2}
    ports:
      - 22/tcp # SSH
      - 53/tcp # DNS
      - 53/udp # DNS
      - 123/udp # NTP
      - 443/tcp # HTTPS
      - 1900/udp # L2 network discovery
      - 3478/tcp # STUN service
      - 6789/tcp # Speedtest
      - 8080/tcp # Device command/control
      - 8443/tcp # HTTPS Web interface + API
      - 10001/udp # Device discovery
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - '${LOCALPATH}/${PATH_UNIFI}:/unifi'
    restart: unless-stopped

  house:
    container_name: house
    image: wolfgangf/house_mgmt:${IMAGE_VERSION_HOUSE}
    hostname: house
    mac_address: ${MAC_HOUSE}
    networks:
      macVlanNetwork:
        ipv4_address: ${IP_HOUSE}
    dns:
      - 127.0.0.1
      - ${DNS1}
      - ${DNS2}
    ports:
      - "80:3000" # Webpage/Backend
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - '${LOCALPATH}/${PATH_HOUSE}:/usr/app/src/dist/data/'
    restart: unless-stopped

networks:
  macVlanNetwork:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
          ip_range: ${IP_RANGE}